print('''
QUESTION NO: 1001
Which of the following ports is commonly used by VoIP phones?
A. 20
B. 143
C. 445
D. 5060

QUESTION NO: 1002
A retail store recently acquired the store next door. The owners would like this store to
support Gigabit Ethernet for up to 328ft (100m). Which of the following is the MOST cost-
effective solution?
A. Cat5
B. Cat 5e
C. Cat 6
D. Cat 7

QUESTION NO: 1003
A technician is investigating an issue with connectivity at customer's location. The technician
confirms that users can access resources locally but not over the internet. The technician
theorizes that the local router has failed and investigates further. The technician's testing
results show that the router is functional; however, users still are unable to reach resources
on the internet. Which of the following describes what the technician should do NEXT?
A. Document the lessons learned.
B. Escalate the issue.
C. Identify the symptoms.
D. Question users for additional information.

QUESTION NO: 1004
A network administrator wants to check all network connections and see the output in integer
form. Which of the following commands should the administrator run on the command line?
A. netstat
B. netstat -a
C. netstat -e
D. netstat -n

QUESTION NO: 1005
A network technician wants to identify which DNS servers a computer is configured to use.
Which of the following commands should the technician use?
A. nbtstat
B. arp
C. nslookup
D. netstat

QUESTION NO: 1006
Which of the following is the next step to take after successfully testing a root cause theory?
A. Determine resolution steps.
B. Duplicate the problem in a lab.
C. Present the theory for approval.
D. Implement the solution to the problem.

QUESTION NO: 1007
A computer engineer needs to ensure that only a specific workstation can connect to port 1
on a switch. Which of the following features should the engineer configure on the switch
interface?
A. Port tagging
B. Port security
C. Port mirroring
D. Port aggregation

QUESTION NO: 1008
SIMULATION

QUESTION NO: 1010
A technician performed a manual reconfiguration of a firewall, and network connectivity was
reestablished. Some connection events that were previously sent to a syslog server are no
longer being generated by the firewall. Which of the following should the technician perform
to fix the issue?
A. Adjust the proper logging level on the new firewall.
B. Tune the filter for logging the severity level on the syslog server.
C. Activate NetFlow traffic between the syslog server and the firewall
D. Restart the SNMP service running on the syslog server.

QUESTION NO: 1011
An engineer is gathering data to determine the effectiveness of UPSs in use at remote retail
locations. Which of the following statistics can the engineer use to determine the availability
of the remote network equipment?
A. Uptime
B. NetFlow baseline
C. SNMP traps
D. Interface statistics

QUESTION NO: 1012
Which of the following is the reason why a company's network may contain a DHCP server?
A. To assign IP addresses to devices on the network
B. To convert IP addresses to fully qualified domain names
C. To provide POP3 and IMAP email functionality
D. To allow secure remote access

QUESTION NO: 1013
Which of the following layers is where TCP/IP port numbers identify which network
application is receiving the packet and where it is applied?
A. 3
B. 4
C. 5
D. 6
E. 7

QUESTION NO: 1014
An employee reports to a network administrator that internet access is not working. Which of
the following should the administrator do FIRST?
A. Establish a theory of probable cause.
B. Identify symptoms.
C. Determine if anything has changed.
D. Ask the user to restart the computer.

QUESTION NO: 1015
A PC user who is on a local network reports very slow speeds when accessing files on the
network server. The user's PC is connecting, but file downloads are very slow when
compared to other users' download speeds. The PC's NIC should be capable of Gigabit
Ethernet. Which of the following will MOST likely fix the issue?
A. Releasing and renewing the PC's IP address
B. Replacing the patch cable
C. Reseating the NIC inside the PC
D. Flushing the DNS cache
''')
answer = input(print("Do you have your answers? yes/no"))
if answer == "yes":
    print('''
Here are the answers to the questions:

QUESTION NO: 1001
Answer: D. 5060
Explanation: VoIP phones commonly use port 5060 for communication.

QUESTION NO: 1002
Answer: B. Cat 5e
Explanation: Cat 5e cable is the most cost-effective solution for supporting Gigabit Ethernet for up to 328ft (100m).

QUESTION NO: 1003
Answer: D. Question users for additional information.
Explanation: Since the router is functional but users still cannot reach resources on the internet, gathering additional information from users can help identify the root cause of the issue.

QUESTION NO: 1004
Answer: D. netstat -n
Explanation: The `netstat -n` command displays network connections and their numerical form (IP addresses and port numbers) in integer format.

QUESTION NO: 1005
Answer: C. nslookup
Explanation: The `nslookup` command is used to query DNS servers to obtain domain name and IP address mapping information.

QUESTION NO: 1006
Answer: A. Determine resolution steps.
Explanation: After successfully testing a root cause theory, the next step is to determine resolution steps to fix the problem.

QUESTION NO: 1007
Answer: B. Port security
Explanation: Port security allows a network engineer to restrict access to a specific switch port based on MAC addresses, ensuring that only the specified workstation can connect to it.

QUESTION NO: 1010
Answer: A. Adjust the proper logging level on the new firewall.
Explanation: Adjusting the logging level on the new firewall to ensure that the appropriate connection events are logged will fix the issue.

QUESTION NO: 1011
Answer: A. Uptime
Explanation: Uptime statistics can be used to determine the availability of remote network equipment by measuring the amount of time the equipment has been operational without any interruptions.

QUESTION NO: 1012
Answer: A. To assign IP addresses to devices on the network
Explanation: The primary purpose of a DHCP server is to dynamically assign IP addresses to devices on the network.

QUESTION NO: 1013
Answer: B. 4
Explanation: TCP/IP port numbers identify which network application is receiving the packet at the Transport layer (Layer 4).

QUESTION NO: 1014
Answer: C. Determine if anything has changed.
Explanation: Before proceeding with troubleshooting, it's important to determine if any changes have occurred that may have caused the reported issue.

QUESTION NO: 1015
Answer: B. Replacing the patch cable
Explanation: Slow file transfer speeds on a Gigabit Ethernet network can often be caused by faulty or substandard patch cables, so replacing the patch cable is likely to fix the issue.
''')
