print('''
QUESTION NO: 681
A device operating at Layer 3 of the OSI model uses which of the following protocols to
determine the path to a different network?
A. STP
B. RTP
C. RIP
D. NTP
E. SIP

QUESTION NO: 682
An administrator would like to allow Windows clients from outside the office to access
workstations without using third-party software.
Which or the following access methods would meet this requirement?
A. Remote desktop gateway
B. Spit tunnel
C. Site-to-site VPN
D. VNC

QUESTION NO: 683
Which of the following BEST prevents unauthorized access to spare workstation inventory?
A. Asset tags
B. Tamper detection
C. Security camera
D. Locking cabinet
E. Smart lockers

QUESTION NO: 684
Which of the following factors should be considered when evaluating a firewall to protect a
datacenter's east-west traffic?
A. Replication traffic between an on-premises server and a remote backup facility
B. Traffic between VMs running on different hosts
C. Concurrent connections generated by Internet DDoS attacks
D. VPN traffic from remote offices to the datacenter's VMs

QUESTION NO: 685
A company with multiple routers would like to implement an HA network gateway with the
least amount of downtime possible. This solution should not require changes on the gateway
setting of the network clients. Which of the following should a technician configure?
A. Automate a continuous backup and restore process of the system's state of the active
gateway.
B. Use a static assignment of the gateway IP address on the network clients.
C. Configure DHCP relay and allow clients to receive a new IP setting.
D. Configure a shared VIP and deploy VRRP on the routers.

QUESTION NO: 686
A fiber patch cable, which was being stored in an unsecure telecommunications closet with
janitorial supplies, was damaged and caused an outage. A network technician replaced the
broken cable with a new cable from a sealed bag. However, this solution did not resolve the
outage. Which of the following is the MOST likely explanation?
A. Incorrect pinout
B. Incorrect transceivers
C. Reversed transmit and receive
D. Dirty optical cables

QUESTION NO: 687
Users in a remote office report that corporate web server pages are taking a long time to
load, whereas users in the main corporate office do not have any issues. Which of the
following is the best metric for a network administrator to check?
A. Jitter across the network
B. Hop-by-hop network latency
C. Server interface CRC errors
D. Server NetFlow data

QUESTION NO: 688
A network administrator is troubleshooting the communication between two Layer 2 switches
that are reporting a very high runt count. After trying multiple ports on both switches, the
issue persists. Which of the following should the network administrator perform to resolve the
issue?
A. Increase the MTU size on both switches.
B. Recertify the cable between both switches.
C. Perform a factory reset on both switches.
D. Enable debug logging on both switches.

QUESTION NO: 689
A company is connected to an ISP, but owns the premise router with an internal CSU/DSU.
Which of the following is considered the demarc?
A. Premise router
B. ISP router
C. Smart jack
D. CSU/DSU

QUESTION NO: 690
A network engineer performed a migration to a new mail server. The engineer changed the
MX record, verified the change was accurate, and confirmed the new mail server was
reachable via the IP address in the A record. However, users are not receiving email. Which
of the following should the engineer have done to prevent the issue from occurring?
A. Change the email client configuration to match the MX record.
B. Reduce the TTL record prior to the MX record change.
C. Perform a DNS zone transfer prior to the MX record change.
D. Update the NS record to reflect the IP address change.
''')
answer = input(print('Do you have your answers? yes/no'))
if answer == 'yes':
	print('''
QUESTION NO: 681
A device operating at Layer 3 of the OSI model uses which of the following protocols to determine the path to a different network?
C. RIP

QUESTION NO: 682
An administrator would like to allow Windows clients from outside the office to access workstations without using third-party software. Which of the following access methods would meet this requirement?
A. Remote desktop gateway

QUESTION NO: 683
Which of the following BEST prevents unauthorized access to spare workstation inventory?
D. Locking cabinet

QUESTION NO: 684
Which of the following factors should be considered when evaluating a firewall to protect a datacenter's east-west traffic?
B. Traffic between VMs running on different hosts

QUESTION NO: 685
A company with multiple routers would like to implement an HA network gateway with the least amount of downtime possible. This solution should not require changes on the gateway setting of the network clients. Which of the following should a technician configure?
D. Configure a shared VIP and deploy VRRP on the routers.

QUESTION NO: 686
A fiber patch cable, which was being stored in an unsecure telecommunications closet with janitorial supplies, was damaged and caused an outage. A network technician replaced the broken cable with a new cable from a sealed bag. However, this solution did not resolve the outage. Which of the following is the MOST likely explanation?
D. Dirty optical cables

QUESTION NO: 687
Users in a remote office report that corporate web server pages are taking a long time to load, whereas users in the main corporate office do not have any issues. Which of the following is the best metric for a network administrator to check?
B. Hop-by-hop network latency

QUESTION NO: 688
A network administrator is troubleshooting the communication between two Layer 2 switches that are reporting a very high runt count. After trying multiple ports on both switches, the issue persists. Which of the following should the network administrator perform to resolve the issue?
B. Recertify the cable between both switches.

QUESTION NO: 689
A company is connected to an ISP, but owns the premise router with an internal CSU/DSU. Which of the following is considered the demarc?
C. Smart jack

QUESTION NO: 690
A network engineer performed a migration to a new mail server. The engineer changed the MX record, verified the change was accurate, and confirmed the new mail server was reachable via the IP address in the A record. However, users are not receiving email. Which of the following should the engineer have done to prevent the issue from occurring?
B. Reduce the TTL record prior to the MX record change.
''')
